### ISSUE TITLE
Google Maps and navigation. 

### ISSUE THREAD

**Issue by elitemantis** [geekydoc/android_device_l70pn#11]
Navigation doesn't work... cant find my localization. (google maps)

**Comment by dicamarques14** [comment]
Gps isn't working so there's no location

**Comment by elitemantis** [comment]
thx for a information.

**Comment by dicamarques14** [comment]
new version should fix gps

**Comment by geekydoc** [comment]
This should be fixed with latest GPS code changes. Closing.
