### ISSUE TITLE
flashlight

### ISSUE THREAD

**Issue by elitemantis** [geekydoc/android_device_l70pn#13]
application flashlight built into the beam does not work... works 1 sec then crash

**Comment by i-marszi** [comment]
Me too, and blocks the touch screen. Locking and unlocking by the power button helps.
Log
02-21 16:39:26.318 8287-8719/com.android.nfc E/NfcService: Watchdog triggered, aborting.
02-21 16:39:26.318 8287-8719/com.android.nfc E/BrcmNfcJni: nfcManager_doAbort: abort()
02-21 16:39:26.319 8287-8719/com.android.nfc A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 8719 (applyRouting)
02-21 16:39:26.371 27988-27988/? E/DEBUG: AM write failure (32 / Broken pipe)
02-21 16:39:26.532 303-940/? E/QCamera2HWI: qcamera::QCamera2HardwareInterface::QCamera2HardwareInterface(int): E 
02-21 16:39:26.532 303-940/? E/QCamera2HWI: value:26006, country value:260, country code:260
02-21 16:39:26.532 303-940/? E/QCamera2HWI: qcamera::QCamera2HardwareInterface::QCamera2HardwareInterface(int) : failed open /sys/bus/i2c/drivers/hi351/6-0040/antibanding
02-21 16:39:26.532 303-940/? E/QCamera2HWI: [KPI Perf] int qcamera::QCamera2HardwareInterface::openCamera(hw_device_t*_): E PROFILE_OPEN_CAMERA camera id 1
02-21 16:39:26.533 303-940/? E/mm-camera-intf: mm_camera_open: dev name = /dev/video2, cam_idx = 2
02-21 16:39:26.540 8319-8737/? E/mm-camera: isp_tintless_open: E: b6f4623d
02-21 16:39:26.551 8319-8737/? E/mm-camera: isp_tintless_bg_pca_get_version: lib returned version 2.53 err=0
02-21 16:39:26.559 8319-8735/? E/mm-camera-sensor: sensor_init:208 enter ctrl 0xb5826028
02-21 16:39:26.560 8319-8738/? E/mm-camera: is_module_start_session: Enter
02-21 16:39:26.560 8319-8738/? E/mm-camera: is_module_start_session: Exit successful
02-21 16:39:26.560 8319-8738/? E/mm-camera: is_module_get_port: Exit successful
02-21 16:39:26.561 8319-8742/? E/hdr: Session id 0x2 started
02-21 16:39:26.573 8319-8735/? E/mm-camera-sensor: sensor_power_up:151 exit
02-21 16:39:26.617 8319-8735/? E/mm-camera-sensor: module_sensor_start_session:460 failed
02-21 16:39:26.617 8319-8735/? E/mm-camera-sensor: module_sensor_start_session:466 failed
02-21 16:39:26.619 303-940/? E/mm-camera-intf: mm_camera_open:  opened, break out while loop
02-21 16:39:26.627 303-940/? E/mm-jpeg-intf: Max picture size 3264 x 2448, WorkBufSize = 12220416
02-21 16:39:26.638 303-940/? E/qomx_image_core: OMX_Init:94] Complete 2
02-21 16:39:26.644 303-940/? E/QCameraParameters: int32_t qcamera::QCameraParameters::setPreviewFpsRange(int, int): Setting preview fps range 5000,30060
02-21 16:39:26.644 303-940/? E/QCameraParameters: int32_t qcamera::QCameraParameters::setFocusMode(const char_): current_normal_focus set to 0
02-21 16:39:26.645 303-940/? E/QCameraParameters: int32_t qcamera::QCameraParameters::setISOValue(const char_): Setting ISO value auto
02-21 16:39:26.645 303-940/? E/QCameraParameters: cam_denoise_process_type_t qcamera::QCameraParameters::getWaveletDenoiseProcessPlate(): WNR format is : 0
02-21 16:39:26.647 303-940/? E/QCameraParameters: int32_t qcamera::QCameraParameters::initDefaultParameters(): multi_window_af_supported = 1
02-21 16:39:26.647 303-940/? E/QCameraParameters: createMultiWindowString: (-420,-420,-140,-140,1),(-140,-420,140,-140,1),(140,-420,420,-140,1),(-420,-140,-140,140,1),(-140,-140,140,140,1),(140,-140,420,140,1),(-420,140,-140,420,1),(-140,140,140,420,1),(140,140,420,420,1),(-220,-220,220,220,1)
02-21 16:39:26.647 303-940/? E/QCameraParameters: int32_t qcamera::QCameraParameters::initDefaultParameters(): multi_window_af value = (-420,-420,-140,-140,1),(-140,-420,140,-140,1),(140,-420,420,-140,1),(-420,-140,-140,140,1),(-140,-140,140,140,1),(140,-140,420,140,1),(-420,140,-140,420,1),(-140,140,140,420,1),(140,140,420,420,1),(-220,-220,220,220,1)
02-21 16:39:26.736 303-8734/? E/QCameraParameters: park void qcamera::QCameraParameters::setHorViewAngle(int, int), cal_hor_view_angle = 54.633331
02-21 16:39:26.754 303-8734/? E/QCameraParameters: park void qcamera::QCameraParameters::setHorViewAngle(int, int), cal_hor_view_angle = 54.633331
02-21 16:39:26.755 303-8734/? E/QCameraParameters: int32_t qcamera::QCameraParameters::setFocusMode(const char_): current_normal_focus set to 0
02-21 16:39:26.763 303-8391/? E/QCamera2HWI: [KPI Perf] static int qcamera::QCamera2HardwareInterface::start_preview(camera_device_): E PROFILE_START_PREVIEW
02-21 16:39:26.764 303-8734/? E/QCameraParameters: cam_denoise_process_type_t qcamera::QCameraParameters::getWaveletDenoiseProcessPlate(): WNR format is : 0
02-21 16:39:26.765 8319-8747/? E/mm-camera: mct_pipeline_add_stream_to_linked_streams: linked streams: 0x80
02-21 16:39:26.766 303-8734/? E/mm-camera-intf: mm_stream_get_v4l2_fmt: Unknown fmt=78
02-21 16:39:26.766 303-8734/? E/QCameraParameters: cam_denoise_process_type_t qcamera::QCameraParameters::getWaveletDenoiseProcessPlate(): WNR format is : 0
02-21 16:39:26.767 8319-8747/? E/mm-camera: mct_pipeline_add_stream_to_linked_streams: linked streams: 0x82
02-21 16:39:26.767 8319-8747/? E/mm-camera: isp_hw_find_primary_cid:300 error cannot find primary sensor format
02-21 16:39:26.775 8319-8747/? E/mm-camera: module_faceproc_client_create:968] Face proc feature mask e 0
02-21 16:39:26.780 8319-8747/? E/mm-camera: [af_port_handle_stream_mode_update] af_port_handle_module_event: af_port->mode_value_still_video = 0
02-21 16:39:26.794 8319-8747/? E/mm-camera: mct_pipeline_send_ctrl_events: Send Set Parm events
02-21 16:39:26.794 8319-8747/? E/mm-camera-sensor: module_sensor_event_control_set_parm:1698 CAM_INTF_PARM_LED_MODE 3 
02-21 16:39:26.797 8319-8747/? E/mm-camera: stats_port_proc_downstream_set_parm: CAM_INTF_PARM_ZOOM
02-21 16:39:26.817 303-8734/? E/mm-camera-intf: mm_stream_request_buf: buf_num = 7, stream type = 7
02-21 16:39:26.818 8319-8747/? E/mm-camera: mct_pipeline_process_set: stream_type = 7
02-21 16:39:26.819 303-8734/? E/QCameraParameters: int qcamera::QCameraParameters::getPreviewHalPixelFormat() const: format 17
02-21 16:39:26.857 303-8734/? E/mm-camera-intf: mm_stream_request_buf: buf_num = 8, stream type = 1
02-21 16:39:26.858 8319-8747/? E/mm-camera: mct_pipeline_process_set: stream_type = 1
02-21 16:39:26.867 8319-8747/? E/mm-camera-sensor: sensor_set_resolution:1481 width 320, height 240
02-21 16:39:26.867 8319-8747/? E/mm-camera-sensor: sensor_set_resolution:1483 stream mask 2 hfr mode 0 fps 30.000000
02-21 16:39:26.899 8319-8747/? E/mm-camera: decide_isp_nums_camif: num_isp = 1
02-21 16:39:26.902 8319-8784/? E/mm-camera: isp_pipeline_get_table_size: ISP_HW_MOD_GET_TABLE_SIZE error, module_id = 1, rc = -1
02-21 16:39:26.902 8319-8784/? E/mm-camera: isp_hw_proc_init_meta_dump: get ISP_PIX_GET_ROLLOFF_TABLE_SIZE error
02-21 16:39:26.902 8319-8747/? E/mm-camera: isp_util_gen_init_stats_cfg: AF, camif_window_width/camif_window_height (1640, 1232)
02-21 16:39:26.902 8319-8747/? E/mm-camera: isp_util_gen_init_stats_cfg: AF, h_num/v_num (0, 0)
02-21 16:39:26.902 8319-8747/? E/mm-camera: isp_util_gen_init_stats_cfg: AF, rout_width/out_height = 320, 240
02-21 16:39:26.902 8319-8747/? E/mm-camera: isp_util_gen_init_stats_cfg: AF, roi (0, 0, 0, 0)
02-21 16:39:26.902 8319-8747/? E/mm-camera: af_port_handle_stream_mode_update: af_port->mode_value_still_video = 1 / af_port->stream_info.stream_type = 1
02-21 16:39:26.902 8319-8747/? E/mm-camera: af_port_handle_stream_mode_update: af_port->mode_value_still_video = 1 / af_port->stream_info.stream_type = 1
02-21 16:39:26.902 8319-8747/? E/mm-camera: af_port_handle_stream_mode_update: Still Mode
02-21 16:39:26.903 8319-8747/? E/mm-camera-sensor: chromatix_load_library:30 Failed to dlopen libchromatix_imx219_snapshot.so: dlopen failed: library "libchromatix_imx219_snapshot.so" not found
02-21 16:39:26.903 8319-8747/? E/mm-camera-sensor: chromatix_load_library:30 Failed to dlopen libchromatix_imx219_preview.so: dlopen failed: library "libchromatix_imx219_preview.so" not found
02-21 16:39:26.903 8319-8747/? E/mm-camera-sensor: load_chromatix:64 load_chromatix: target_country is cm_l70pn
02-21 16:39:26.903 8319-8747/? E/mm-camera-sensor: vendor/qcom/proprietary/mm-camera/mm-camera2/media-controller/modules/sensors/chromatix/0301/libchromatix/chromatix_imx219_475t/common/chromatix_imx219_common.c : start chromatix process 
02-21 16:39:26.903 8319-8747/? E/mm-camera-sensor: vendor/qcom/proprietary/mm-camera/mm-camera2/media-controller/modules/sensors/chromatix/0301/libchromatix/chromatix_imx219_475t/common/chromatix_imx219_common.c : fd_chromatix=-1 
02-21 16:39:26.903 8319-8747/? E/mm-camera-sensor: vendor/qcom/proprietary/mm-camera/mm-camera2/media-controller/modules/sensors/chromatix/0301/libchromatix/chromatix_imx219_475t/common/chromatix_imx219_common.c: chromatix : Use default params
02-21 16:39:26.904 8319-8747/? E/mm-camera-sensor: load_chromatix:64 load_chromatix: target_country is cm_l70pn
02-21 16:39:26.904 8319-8747/? E/mm-camera-sensor: vendor/qcom/proprietary/mm-camera/mm-camera2/media-controller/modules/sensors/chromatix/0301/libchromatix/chromatix_imx219_475t/common/chromatix_imx219_common.c : start chromatix process 
02-21 16:39:26.904 8319-8747/? E/mm-camera-sensor: vendor/qcom/proprietary/mm-camera/mm-camera2/media-controller/modules/sensors/chromatix/0301/libchromatix/chromatix_imx219_475t/common/chromatix_imx219_common.c : fd_chromatix=-1 
02-21 16:39:26.904 8319-8747/? E/mm-camera-sensor: vendor/qcom/proprietary/mm-camera/mm-camera2/media-controller/modules/sensors/chromatix/0301/libchromatix/chromatix_imx219_475t/common/chromatix_imx219_common.c: chromatix : Use default params
02-21 16:39:26.904 8319-8747/? E/mm-camera-sensor: chromatix_get_ptr:250 failed: chromatix ptr NULL
02-21 16:39:26.909 8319-8747/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x506e in tid 8747 (mm-qcamera-daem)
02-21 16:39:27.121 728-1008/system_process E/WifiStateMachine: WifiStateMachine L2Connected CMD_START_SCAN source -2 795, 799 -> obsolete
02-21 16:39:27.643 27988-27988/? E/DEBUG: AM write failure (32 / Broken pipe)
02-21 16:39:27.971 8802-8823/com.android.nfc E/NfcAdaptation: NfcAdaptation::Initialize: ver=NFCDROID-AOSP_L_00.01 nfa=NFA_PI_1.03.66+
02-21 16:39:28.067 8831-8831/? E/mm-camera: server_process_module_init:59, int mods
02-21 16:39:28.070 8831-8831/? E/mm-camera-sensor: module_sensors_subinit:140 session 2 subdev 3 not present, reset to -1
02-21 16:39:28.076 8831-8831/? E/mm-camera: isp_util_gen_hws_caps: integrating kernel vfe is pending
02-21 16:39:28.078 8831-8831/? E/mm-camera: isp_tintless_create: using BG stats for tintless!, isp version = 20
02-21 16:39:28.079 8831-8831/? E/mm-camera: is_module_init: Enter
02-21 16:39:28.079 8831-8831/? E/mm-camera: cpp_hardware_find_subdev:903: no cpp device found.
02-21 16:39:28.079 8831-8831/? E/mm-camera: cpp_hardware_create:40: error: cannot find cpp subdev
02-21 16:39:28.079 8831-8831/? E/mm-camera: cpp_module_create_cpp_ctrl:164, failed, cannnot create cpp hardware instance
02-21 16:39:28.079 8831-8831/? E/mm-camera: cpp_module_init:54 failed
02-21 16:39:28.079 8831-8831/? E/mm-camera: vpe_module_init:26 name=vpe
02-21 16:39:28.079 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=video0 entity.revision=0
02-21 16:39:28.079 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev0 entity.revision=0
02-21 16:39:28.079 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev1 entity.revision=0
02-21 16:39:28.079 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev2 entity.revision=0
02-21 16:39:28.079 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev3 entity.revision=0
02-21 16:39:28.079 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev4 entity.revision=0
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev5 entity.revision=0
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev6 entity.revision=0
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev7 entity.revision=0
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev8 entity.revision=0
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev9 entity.revision=0
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=v4l-subdev10 entity.revision=0
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:711: done enumerating media entities
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=video1 entity.revision=0
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:711: done enumerating media entities
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:716: entity.name=video2 entity.revision=0
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:711: done enumerating media entities
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:683: no more media devices
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_find_subdev:728: no vpe device found.
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_hardware_create:31: error: cannot find vpe subdev
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_module_create_vpe_ctrl:141, failed, cannnot create vpe hardware instance
02-21 16:39:28.080 8831-8831/? E/mm-camera: vpe_module_init:34 failed
02-21 16:39:28.080 8831-8831/? E/mm-camera: c2d_module_init:28 name=c2d
02-21 16:39:28.080 8831-8831/? E/mm-camera-img: img_core_get_comp:37] role 0 name qcom.wavelet
02-21 16:39:28.080 8831-8831/? E/mm-camera-img: img_core_get_comp:42] comp_index[0] role 0 name qcom.wavelet
02-21 16:39:28.080 8831-8831/? E/mm-camera-img: img_core_get_comp:47] find component role 0 name qcom.wavelet
02-21 16:39:28.081 8831-8831/? E/mm-camera-img: wd_comp_load:1571] WD library loaded successfully dsp 0
02-21 16:39:28.081 8831-8831/? E/mm-camera-img: module_imglib_create_port:1254 portname imglib_d2_i0
02-21 16:39:28.081 8831-8831/? E/mm-camera-img: img_core_get_comp:37] role 2 name qcom.faceproc
02-21 16:39:28.081 8831-8831/? E/mm-camera-img: img_core_get_comp:42] comp_index[0] role 0 name qcom.wavelet
02-21 16:39:28.081 8831-8831/? E/mm-camera-img: img_core_get_comp:42] comp_index[1] role 1 name qcom.hdr
02-21 16:39:28.081 8831-8831/? E/mm-camera-img: img_core_get_comp:42] comp_index[2] role 2 name qcom.faceproc
02-21 16:39:28.081 8831-8831/? E/mm-camera-img: img_core_get_comp:47] find component role 2 name qcom.faceproc
02-21 16:39:28.082 8831-8831/? E/mm-camera-img: img_core_get_comp:37] role 1 name qcom.hdr
02-21 16:39:28.082 8831-8831/? E/mm-camera-img: img_core_get_comp:42] comp_index[0] role 0 name qcom.wavelet
02-21 16:39:28.082 8831-8831/? E/mm-camera-img: img_core_get_comp:42] comp_index[1] role 1 name qcom.hdr
02-21 16:39:28.082 8831-8831/? E/mm-camera-img: img_core_get_comp:47] find component role 1 name qcom.hdr
02-21 16:39:28.084 8831-8831/? E/mm-camera-img: hdr_comp_load:1137] HDR library loaded successfully
02-21 16:39:28.084 8831-8831/? E/hdr: Port hdr_dummy initialized
02-21 16:39:28.084 8831-8831/? E/mm-camera-img: module_imglib_create_dummy_port:1362 portname imglib_dymmy_d1_i0
02-21 16:39:28.267 8802-8827/com.android.nfc E/NxpHal: i2c_fragmentation_status existing
02-21 16:39:28.268 8802-8827/com.android.nfc E/NxpFwDnld: Freeing Mem for Dnld Context..
02-21 16:39:30.600 8802-8827/com.android.nfc E/BrcmNfcJni: nfaDeviceManagementCallback: NFA_DM_GET_CONFIG failed
02-21 16:39:30.600 8802-8823/com.android.nfc E/BrcmNfcJni: enableDisableLptd: Config TLV length 0 returned is too short
02-21 16:39:30.601 8802-8827/com.android.nfc E/BrcmNfcJni: nfaConnectionCallback: unknown event ????
02-21 16:39:30.676 303-8850/? E/AudioPolicyManager: isOffloadSupported: stream_type != MUSIC, returning false
02-21 16:39:30.676 303-8850/? E/AudioPolicyManager: isOffloadSupported: stream_type != MUSIC, returning false
02-21 16:39:30.684 8802-8836/com.android.nfc E/NxpHal: CORE_RESET_NTF received!
02-21 16:39:30.684 8802-8836/com.android.nfc E/NxpHal: phNxpNciHal_emergency_recovery: abort()
02-21 16:39:30.684 8802-8827/com.android.nfc E/BrcmNfcNfa: reset notification!!:0xa0 
02-21 16:39:30.684 8802-8827/com.android.nfc E/BrcmNfcNfa: NCI version mismatch!!:0x10 != 0x00 
02-21 16:39:30.684 8802-8827/com.android.nfc E/BrcmNfcNfa: NFCC version is too old
02-21 16:39:30.684 8802-8827/com.android.nfc E/BrcmNfcNfa: Failed to reset NFCC
02-21 16:39:30.739 303-8871/? E/AudioPolicyManager: isOffloadSupported: stream_type != MUSIC, returning false
02-21 16:39:30.740 303-8871/? E/AudioPolicyManager: isOffloadSupported: stream_type != MUSIC, returning false
02-21 16:39:30.790 303-8878/? E/AudioPolicyManager: isOffloadSupported: stream_type != MUSIC, returning false
02-21 16:39:30.790 303-8878/? E/AudioPolicyManager: isOffloadSupported: stream_type != MUSIC, returning false
02-21 16:39:31.855 303-8734/? E/mm-camera-intf: mm_stream_streamon: ioctl VIDIOC_STREAMON failed: rc=-1
02-21 16:39:31.858 303-8734/? E/mm-camera-intf: mm_channel_start: start stream failed at idx(1)
02-21 16:39:31.859 303-8734/? E/mm-camera-intf: mm_stream_streamoff: STREAMOFF failed: Bad address
02-21 16:39:31.859 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.859 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.859 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.859 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.859 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.859 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.859 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.859 303-8734/? E/mm-camera-intf: mm_stream_fsm_reg: invalid state (5) for evt (8), in(0x0), out(0x0)
02-21 16:39:31.859 303-8734/? E/mm-camera-intf: mm_stream_unreg_buf: fd=42, VIDIOC_REQBUFS failed, rc=-1
02-21 16:39:31.859 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.859 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.860 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.860 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.860 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.860 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.860 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.860 303-8734/? E/QCameraStream: int32_t qcamera::QCameraStream::putBufs(mm_camera_map_unmap_ops_tbl_t_): map_stream_buf failed: -1
02-21 16:39:31.867 303-8734/? E/QCameraStream: Failed to map stream info buffer
02-21 16:39:31.868 303-8734/? E/QCameraStream: Failed to map stream info buffer
02-21 16:39:31.870 728-8756/system_process E/RequestThread-1: Received device exception during capture call: 
                                                              java.lang.RuntimeException: startPreview failed
                                                                  at android.hardware.Camera.startPreview(Native Method)
                                                                  at android.hardware.camera2.legacy.RequestThreadManager.startPreview(RequestThreadManager.java:280)
                                                                  at android.hardware.camera2.legacy.RequestThreadManager.doPreviewCapture(RequestThreadManager.java:322)
                                                                  at android.hardware.camera2.legacy.RequestThreadManager.access$1600(RequestThreadManager.java:63)
                                                                  at android.hardware.camera2.legacy.RequestThreadManager$5.handleMessage(RequestThreadManager.java:784)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
02-21 16:39:31.872 728-1003/system_process E/TorchService: Camera error: camera=android.hardware.camera2.impl.CameraDeviceImpl@3c4cbd29 error=1
02-21 16:39:31.888 728-8728/system_process E/Camera: Error 100
02-21 16:39:31.888 728-8728/system_process E/RequestThread-1: Received error 100 from the Camera1 ErrorCallback
02-21 16:39:35.876 728-8756/system_process E/RequestThread-1: Timed out while waiting for prior requests to complete.
02-21 16:39:35.880 728-8756/system_process E/CameraDeviceState: Cannot call capture while in state: 0
02-21 16:39:35.881 728-8756/system_process E/CameraDeviceState: Cannot call idle while in state: 0
02-21 16:39:35.896 303-303/? E/QCamera2HWI: [KPI Perf] static void qcamera::QCamera2HardwareInterface::stop_preview(camera_device_): E PROFILE_STOP_PREVIEW
02-21 16:39:35.903 303-303/? E/QCamera2HWI: int qcamera::QCamera2HardwareInterface::closeCamera() : E
02-21 16:39:35.906 303-303/? E/QCamera2HWI: mParameters.deinit()
02-21 16:39:35.906 303-303/? E/QCamera2HWI: closeCamera: unlock(m_parm_lock)
02-21 16:39:35.909 303-303/? E/QCamera2HWI: m_cbNotifier.exit()
02-21 16:39:35.909 303-303/? E/QCameraPostProc: int32_t qcamera::QCameraPostProcessor::stop() : E, m_bInited = 1
02-21 16:39:35.909 303-303/? E/QCameraPostProc: int32_t qcamera::QCameraPostProcessor::stop() : X
02-21 16:39:35.912 303-303/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:123:/dev/adsprpc-smd device initialization error: Operation not permitted
02-21 16:39:35.912 303-303/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:173::error: -1: dev != -1
02-21 16:39:35.912 303-303/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:214::error: -1: 0 == (nErr = remotectl_open(name, (int_)ph, dlerrstr, sizeof(dlerrstr), &dlerr))
02-21 16:39:35.912 303-303/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:123:/dev/adsprpc-smd device initialization error: Operation not permitted
02-21 16:39:35.912 303-303/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:173::error: -1: dev != -1
02-21 16:39:35.915 303-303/? E/qomx_image_core: OMX_Deinit:118] Complete
02-21 16:39:35.918 303-303/? E/QCameraPostProc: int32_t qcamera::QCameraPostProcessor::deinit(): Jpeg closed, rc = 0, mJpegClientHandle = a00
02-21 16:39:35.918 303-303/? E/QCamera2HWI: m_postprocessor.deinit()
02-21 16:39:35.918 303-303/? E/QCamera2HWI: m_channels->stop
02-21 16:39:35.920 303-303/? E/QCamera2HWI: int qcamera::QCamera2HardwareInterface::closeCamera() : X

**Comment by geekydoc** [comment]
The flashlight works properly in the last build for both cameras
