### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by Turbolqk** [geekydoc/android_device_l70pn#18]
Doesnt work, which i think is because Lg fino has no magnetic sensor. Ether that or its broken.

**Comment by meganukebmp** [comment]
How about you provide more information.

**Comment by Turbolqk** [comment]
In quick settings, where you turn on Wifi, Mobile Data etc. you can add a compass from notification panel settings. But in order for that to work, you got to have a magnetic field sensor. Currently when switched on, it just says "Starting compass", but it eventually never does start. As far as i know, that happens because d290n has no such sensor.

**Comment by pedrofrade1996** [comment]
On stock rom the Google Maps recognized compass. On CyanogenMod it doesn't.

**Comment by meganukebmp** [comment]
Fixed in latest build.
