### ISSUE TITLE
network internet 3g/2g 

### ISSUE THREAD

**Issue by mountaser** [geekydoc/android_device_l70pn#21]
i cant connect to the internet via 3g or 2g networks and thier is a (!) on the signal logo
i cheked the apn setings and everything is set 
i can make calls and send messages and using internet via wifi

**Comment by ProudlyTM** [comment]
Just put your phone to Airplane mode and then turn Airplane mode off.

**Comment by meganukebmp** [comment]
Issue re opened
Seems to be broadband issue. Looking in to it.
