### ISSUE TITLE
Camera doesnt work

### ISSUE THREAD

**Issue by oswaldobiolo** [geekydoc/android_device_l70pn#26]
Hi guys.

Are you working in resolve this issue?
Neither rear and front camera are working.

Regards.

**Comment by geekydoc** [comment]
Hello, I am currently working on it. We are at the stage where both cameras get recognized, but the manipulation of some of the camera parameters fails. I will only upload the code and build when I manage to get some images.

**Comment by oswaldobiolo** [comment]
Thanks geekydoc. 

I'll waiting for good news.
