### ISSUE TITLE
Quando sai a proxima atualizaçao?

### ISSUE THREAD

**Issue by SLTUTORIAL** [geekydoc/android_device_l70pn#27]
acho que o Bug do cabo usb não e tao de se preocupar pois conseguir resolve esse bug de uma forma facil,em que o dispositivo naão desligue o pc, e que consiga ler a memoria interna/externa

mais gostaria de saber quando saíra a proxima atualizaçao,e qual bug sera resolvido nela?

desde já agradeço pelo resposta!

**Comment by oswaldobiolo** [comment]
Plz,  in English!

**Comment by SLTUTORIAL** [comment]
I think what the Cape Bug USB NO is so worrying for Getting determination This bug An easy way in the device does not turn off the PC , and what can read an internal / external memory

More would like to know when he went out the next update , and which bug will be fixed in the next update ?

Thank you very much in advance!

**Comment by geekydoc** [comment]
Hello, we are aware of the issue with the USB Driver and we are looking for a fix. We are now focusing on fixing the issues with the cameras, then there will be a new update

Thank you
