### ISSUE TITLE
There are new update

### ISSUE THREAD

**Issue by McZodek** [geekydoc/android_device_l70pn#28]
already you have the update with which already work bed? or the 20.03.2016 and it works ?

**Comment by mountaser** [comment]
20.03.2016----------------------------------------------------------
Fixed rotation sensor.
Fixed magnetic sensor.
Deactivated SELinux for now.
28.02.2016----------------------------------------------------------
Fixed GPS.
21.02.2016-----------------------------------------------------------
Fixed screen flicker, burn-ins and similar problems.
19.02.2016-----------------------------------------------------------
Swapped out GPU driver. Artifacts and weird burn-ins
should be gone.
17.02.2016-----------------------------------------------------------
Fixed battery not being recognized
11.02.2016 -----------------------------------------------------------
Fixed device Power button. It can now be waked.
Fixed RAMDUMP's, the device will no longer enter them.
02.02.2016-----------------------------------------------------------
Fixed softkeys not appearing.
31.1.2016 -------------------------------------------------------------
Initial build.
####-------------------------------------------------------
