### ISSUE TITLE
Bug(s)

### ISSUE THREAD

**Issue by RenegadeX44** [geekydoc/android_device_l70pn#3]
I'm using D290N, Cyanogenmod 12.1.
Few bugs I encountered:
1. Screen sometime freezes and turning the screen off then on fixes it.
2. Sometimes when I reboot my phone, the CM logo passes, then the Loading apps screen, the one after CM logo, stays still and I have to remove the battery to make it turn on.
3. Double tap to wake.
4. GPS doesn't work.
5. Placing enable/disable torch in the Navigation Circle (long pressing a soft key and pulling it to open a certain action), makes the phone restart. I'm certain it's cause of the camera and the LED that's not working currently in the build, but just posting it to be sure.

**Comment by geekydoc** [comment]
1 and 2. I do not experience any of these issues. Can you please provide some more information about how and when these happen (any applications open, the state of the device, whether you are on usb charger/battery) Also, providing logcats and the kernel log would be very helpful.
3 and 4. We do know that. We are trying to fix them.

**Comment by RenegadeX44** [comment]
1. Appears usually when I open Viber (most of the time), but it can appear sometime on some other apps when I type, might be something with the keyboard.
2. This happens when I reboot to recovery (using the advanced restart provided in the Developers menu in the Settings, usually do it to check the battery status (only way currently)) and then restart the phone through the recovery itself by clicking Reboot, then System (using TWRP 3.0.0). It goes through the LG logo, then goes to the CM logo, then the next screen, which I presume, loads the apps cause of the ART in the Lollipop. That screen sometimes gets stuck and I have to remove the battery and reinsert it. In 100% times, after doing the battery removal-reinsertion, the phone boots normally to system.

**Comment by geekydoc** [comment]
I will check out both of the problems, although i cannot reproduce them. There are some errors coming from the kernel log, so maybe one of them might be causing the hangs. Please note that the battery issue is fixed, and the changes are commited to the kernel. If you can build the rom yourself, I advice you to do so. A new build will be uploaded to the rom thread soon along with a link to it.

Thank you

**Comment by RenegadeX44** [comment]
That is good to know, I will wait for the ROM to be uploaded cause I don't have the knowledge to build it myself.

Any ETA on the updated ROM?

**Comment by RenegadeX44** [comment]
Found another bug, number 5.
1. Placing enable/disable torch in the Navigation Circle (long pressing a soft key and pulling it to open a certain action), makes the phone restart. I'm certain it's cause of the camera and the LED that's not working currently in the build, but just posting it to be sure.

**Comment by dicamarques14** [comment]
How to test touch freeze
Go to system settings, notification drawer,  select and order tiles
As soon as you enter the device wont respond to any touch and if you lock it and unlock it the touch works agains
The screen isnt frozen, only the touch that stops
