### ISSUE TITLE
Disappearing Icons

### ISSUE THREAD

**Issue by Trater** [geekydoc/android_device_l70pn#30]
After every reboot, random icons are disappearing from home screen.

**Comment by geekydoc** [comment]
I am not able to reproduce this issue. Can you provide some logs ?

**Comment by meganukebmp** [comment]
This is most likely a CM specific bug and not related to us. We have not changed anything system wise. Report the problem directly to the Cyanogenmod Team.

**Comment by meganukebmp** [comment]
This is most likely a CM specific bug and not related to us. We have not changed anything system wise. Report the problem directly to the Cyanogenmod Team.

**Comment by meganukebmp** [comment]
This is most likely a CM specific bug and not related to us. We have not changed anything system wise. Report the problem directly to the Cyanogenmod Team.

**Comment by meganukebmp** [comment]
This is most likely a CM specific bug and not related to us. We have not changed anything system wise. Report the problem directly to the Cyanogenmod Team.

**Comment by meganukebmp** [comment]
This is most likely a CM specific bug and not related to us. We have not changed anything system wise. Report the problem directly to the Cyanogenmod Team.

**Comment by meganukebmp** [comment]
This is most likely a CM specific bug and not related to us. We have not changed anything system wise. Report the problem directly to the Cyanogenmod Team.

**Comment by meganukebmp** [comment]
This is most likely a CM specific bug and not related to us. We have not changed anything system wise. Report the problem directly to the Cyanogenmod Team.

**Comment by meganukebmp** [comment]
This is most likely a CM specific bug and not related to us. We have not changed anything system wise. Report the problem directly to the Cyanogenmod Team.

**Comment by meganukebmp** [comment]
This is most likely a CM specific bug and not related to us. We have not changed anything system wise. Report the problem directly to the Cyanogenmod Team.
