### ISSUE TITLE
CM 12 not installing on lg l fino

### ISSUE THREAD

**Issue by noorshahzeb** [geekydoc/android_device_l70pn#32]
I have installed latest TWRP on my lg l fino D295 and when i try to install CM12 on my device it always says failed it says
Rom is 170 pn your device is 170 dns what does it mean plz help how to install it successfully

**Comment by meganukebmp** [comment]
Rom currently does not officially support D295. Although it can be installed using a updater-script modification we do not advise this until we fully fix D290N. After we fix it we will create 2 separate builds for both devices.
