### ISSUE TITLE
Data from SD card missing at phone restart

### ISSUE THREAD

**Issue by rpallares** [geekydoc/android_device_l70pn#38]
Firstly, thanks for this cyanogen rom.

Each time I restart the phone, desktop shortcuts disappear for applications installed on the SD card.
Applications still exists, and I just have to recreate shortcuts.

I don't know why, but the facebook app forget only the password when I restart. By against the email is saved.

It seams that the system don't load some data from SD card.
I don't have log files, sorry

**Comment by meganukebmp** [comment]
Depends on how you mount the aplications on the SD card. If you're using a third party tool such as Link2SD. That's a problem with the software and not the ROM.

**Comment by rpallares** [comment]
Hi,
I don't use any third party tool to move applications on SD card.
I just go to Applications > App > Move to SD Card
Navigating into closed request I saw #30 that seems to be the same Issue.
Can you tell me what log file I should transfert to help?

**Comment by meganukebmp** [comment]
Seems to be a filesystem error. Have you tried formatting all partitions?

**Comment by rpallares** [comment]
I will try. I'm installing the new release :)

**Comment by rpallares** [comment]
I still have the same problem. I formated all before install the las release.
May be the problem came from my SD card.
If I test with a new one I'll keep you informed.
