### ISSUE TITLE
Mobile data problem

### ISSUE THREAD

**Issue by migueltopsp** [geekydoc/android_device_l70pn#39]
the phone can not connect to the mobile data, already tried by the plane mode, restart, I am already set up several APN's and still not working ...
when I go to the options sim card, appears to have no number, which mean that the phone status is unknown, do not know if there's anything there, but I can not change the phone's status.

Will the new build 07.18.2016 D290N fixes it ?, because I'm using the previous build.

Extra note:
can I update a build to another without having to format?

**Comment by meganukebmp** [comment]
Looking in to problem

**Comment by migueltopsp** [comment]
I found out yesterday that these problems may be with IMEI , as this when I type \* # 06 # does not appear , I've tried several ways and the sim card is not recognized , there are other ways to change the IMEI but found no solution that works , without having to install drivers , because these crash (BSOD ) windows , right now I'm looking for a solution on linux , but i need someone that can help me solve this !

**Comment by ProudlyTM** [comment]
@migueltopsp yes, you can update a build without wiping!
