### ISSUE TITLE
Sometimes screen gets a burn mark

### ISSUE THREAD

**Issue by dicamarques14** [geekydoc/android_device_l70pn#4]
Sometimes when the device is locked, someti. E goes wrong with the screen and it shows a fixed image, causing burn marks
http://i.imgur.com/9lP6uh6.png
http://i.imgur.com/aXctmQm.png
http://i.imgur.com/8if2fvo.jpg
The light is working fine, maybe the screen is not being  turned off properly

**Comment by RenegadeX44** [comment]
Seconded, happens to me too.
It's kinda hard to explain when it occurs and why. It just shows those white "burns" around the edges which disappear after a while when using the device.

**Comment by ProudlyTM** [comment]
It happens to me too. We are still working on that bug.

**Comment by noname123321** [comment]
i have this same bug, and i see pixels, is it dangerous? this bug can do something with my display?

**Comment by RenegadeX44** [comment]
If I may add (don't want to open a new issue, I will if needed), a graphical artifact as blue flashing color over the screen appears sometime when using the device.

**Comment by dicamarques14** [comment]
thats already known, graphic artifacts

**Comment by geekydoc** [comment]
Fixed. Screen now turns off properly
