### ISSUE TITLE
Could you please give me some help about how to build a ROM?

### ISSUE THREAD

**Issue by xjl12** [geekydoc/android_device_l70pn#41]
I am building H30-C00,it similar to this one because they use MSM8610 CPU.
I have downloaded the source code and success compiled,but the devices can't start.I use "adb logcat" and it said:
E/HAL     (  321): load: module=/system/lib/hw/camera.msm8610.so
E/HAL     (  321): dlopen failed: cannot locate symbol "_ZN7android10VectorImpl19reservedVectorImpl1Ev" referenced by "camera.msm8610.so"...
E/CameraService(  321): Could not load camera HAL module
Could you please give me some advice?

**Comment by meganukebmp** [comment]
The camera HAL is crashing. Thats not the reason for it not boooting tho. The hal crash is caused because of misscomunication with the driver.

**Comment by xjl12** [comment]
I think this may be related to the kernel.Because I build CM11 use Android 4.3's kernel,so I want to build CM10.I don't know this is not right.This can do?

**Comment by xjl12** [comment]
Maybe,I should do some changes in the source.Have you did any changes in the source about QCOM MSM8610?

**Comment by meganukebmp** [comment]
The kernel source has changed drastically over time. The CM12.1 source should work only with CM12.1. Use the CM11 branch for CM11.

**Comment by xjl12** [comment]
Thank you very much for your help!
