### ISSUE TITLE
Adoptable storage

### ISSUE THREAD

**Issue by sneakyc9** [geekydoc/android_device_l70pn#42]
When I try to format my class 10, 16 gb lexar sd card as internal storage it gets stuck at %20 and after a few minutes it cancels the format and sd gets corrupted after the cancel.

**Comment by geekydoc** [comment]
Hello, this seems to be android specific and sd card specific. There is a forum discussion here about it: https://forums.lenovo.com/t5/Moto-X-Pure-Moto-X-Style/Bug-with-SD-Card-Internal-Storage-Formatting/td-p/3234382
