### ISSUE TITLE
Skype has stopped

### ISSUE THREAD

**Issue by mbackonja** [geekydoc/android_device_l70pn#45]
I just installed latest version and everything is great but only issue I have is running skype. I installed skype but I can't open skype "Skype has stopped".

**Comment by geekydoc** [comment]
Take a look at this. This is a skype issue: https://community.skype.com/t5/Android/After-update-to-Android-6-Marshmallow-Skype-can-not-start/td-p/4169237

**Comment by mbackonja** [comment]
I found someone answered 

> It turns out that if I change the language of my phone from Bulgarian to English, my skype will work... So please fix this as soon as possible!!!!

 and my phone is on Serbian Cyrillic (and Bulgarian is also Cyrillic). So, I'm waiting for skype update. Thanks!
