### ISSUE TITLE
Gps not working

### ISSUE THREAD

**Issue by ercerd** [geekydoc/android_device_l70pn#46]
Gps is not working here. Tested with every build of CM13.
Not working even with the "cm13.0-20161111-UNOFFICIAL" build.
My phone is D290TR.

**Comment by geekydoc** [comment]
Could you provide a logcat from when the gps is turned on? On what app have you tested the gps?

**Comment by ercerd** [comment]
Tested with "GPS Status and Toolbox", "Google Maps" and some other apps with names including "GPS".
When using Google Maps it can't find location by hardware only.
And here is the logcat i could get: 
[logcat3.txt](https://github.com/geekydoc/android_device_l70pn/files/588191/logcat3.txt)

**Comment by geekydoc** [comment]
From the logcat, gps Hal seems to be working and sending data, the position is calculated and data are sent back to userspace. I cannot figure out why you do not get the gps data in the applications. Could you try deleting agps data and clean applications cache and retry?

**Comment by ercerd** [comment]
Ok. I get a location on a very clear and open place after about 10 mins. But very unstable. I couldnt get any location on my balcony of my apartment though. Gps was not perfect on stock, but i was able to use navigation apps. Now i can't. Could this be a hardware problem?
Anyway thanks for your time.

**Comment by geekydoc** [comment]
It could be a hardware issue ( a return to stock would clear this out) or a software (HAL) limitation. I will try to implement some different gps code, maybe this gets gps to lock faster. I hope it will be coming on the next updates.
