### ISSUE TITLE
wlan disconnect

### ISSUE THREAD

**Issue by Flauschi1981** [geekydoc/android_device_l70pn#48]
hi i have problem with wlan. it works for few minutes and it disconnect than reconnect and again. i have and a bug with the Flixtervideo app. The app open bat can not playbak the videos! plz fix it! thx

greetings (sry for my bad english)

**Comment by geekydoc** [comment]
Wlan bug is marked as fixed in the latest releases. What version of the rom are you using?

For the video playback issue, please install android webview from the playstore.

**Comment by Flauschi1981** [comment]
cm13.0-20161111-UNOFFICIAL

**Comment by Flauschi1981** [comment]
and no with webview it dont work with flixter! when i klick on watch then nothing....

but thx ^^

**Comment by geekydoc** [comment]
I will check out the issue with wlan again.

For the video playback, can you check if av.streaming.offload.enable build property is set to false? If it is set to true, then change it to false, reboot and try again. I will turn it back to false by default in the upcoming release.

**Comment by Flauschi1981** [comment]
sry but where i can check "av.streaming.offload.enable" ?

**Comment by Flauschi1981** [comment]
and the next release can i update it, in my handy "over the phone, CyanogenMod-Updates" ? or must be over "TWRP"?

**Comment by geekydoc** [comment]
Simpler way to check the properties is get an app like "Kernel Adiutor" , this app has a build.prop editor in it. You can check and edit the properties if needed. 
About updates, I think you mean the CyanogenMod updater? Currently there is no support for it on our device. You will have to download the zip and dirty-flash through TWRP.

**Comment by Flauschi1981** [comment]
ok i check and "av.streaming.offload.enable" is "false" other solution for flixster app?

greetings and thx ^^

**Comment by geekydoc** [comment]
Could you try to play an online video file through another app? If it works, then the issue is app specific.

**Comment by Flauschi1981** [comment]
youtube works

**Comment by akks1981** [comment]
but with the Flixster app u can whatch legal Blueray kopies

**Comment by Flauschi1981** [comment]
ok flixster have problems with rooted handys....ok solved but plz check wlan problems!?

big thx for ur help

**Comment by Flauschi1981** [comment]
ok wlan issues seem too solved with build cm13.0-20161122-UNOFFICIAL!


greetings
