### ISSUE TITLE
moving all the apps (excluding system apps) to the external storage not work

### ISSUE THREAD

**Issue by Flauschi1981** [geekydoc/android_device_l70pn#49]
cm13.0-20161206-UNOFFICIAL

"NOTE: This update also includes a patched android framework (patch done by @g-pl ), which enables moving all the apps (excluding system apps) to the external storage."

not work ?

**Comment by g-pl** [comment]
Have you enabled adoptable storage?

**Comment by Flauschi1981** [comment]
no

**Comment by g-pl** [comment]
so actually the patch works with adoptable storage, not external storage

**Comment by Flauschi1981** [comment]
ah ok thx :)

**Comment by Flauschi1981** [comment]
ok solved! thx
