### ISSUE TITLE
Battery issue

### ISSUE THREAD

**Issue by RenegadeX44** [geekydoc/android_device_l70pn#5]
After flashing the new boot.img with the battery fix, the battery is now shown and charging works. 
But when I turn my phone off and place it on a charger, the battery image, instead of showing percentage and charging, it shows "?", like before.

**Comment by geekydoc** [comment]
Yes, I know that. It still needs some fixes.

Thank you

**Comment by proudlytm** [comment]
Can somebody give me the new boot.img on xda? Thank you.

**Comment by meganukebmp** [comment]
**THIS IS NOT A CHAT**
