### ISSUE TITLE
Mobile data

### ISSUE THREAD

**Issue by RenegadeX44** [geekydoc/android_device_l70pn#7]
Sometimes after using the device for a period of time, without any internet connection (both WiFi and data off), turning Mobile Data on does nothing ("!" next to the signal, like no Mobile Data is on). Restarting the phone fixes it.

**Comment by RenegadeX44** [comment]
https://www.dropbox.com/s/08kssouae1bbpec/2016-02-19-12-10-03.txt?dl=0
Logcat to this issue when I turn it off and turn it on and it doesn't actually turn the Mobile Data on.

**Comment by pedrofrade1996** [comment]
In my experience the "!" mark on the Mobile Data icon is due to "time and date" problem. Try to change the time, or the location of the time (e.g. London (+0) Casa Blanca (-1) )

If you have any question about my response to you don't hesitate to reply and ask.

Hope this helps you

**Comment by RenegadeX44** [comment]
Seems like the "!" still occurs on the data icon in the status bar when both WiFi and Data are off.
Tried messing around with the time and date but with no success.

**Comment by pedrofrade1996** [comment]
Sorry to her that, for me it worked. You must have some settings changed. I get no "!" after correctly changing the time.

**Comment by RenegadeX44** [comment]
It looks like the "!" in the Data icon is just a "mask". When I turn it on it actually works.

**Comment by RenegadeX44** [comment]
Scrap that, not true, it sometimes works, sometimes it doesn't.

**Comment by geekydoc** [comment]
I personally can connect to the net through data network any time. And I always get the "!" mark. Your issue is kept in mind. That symbol shouldn't be there. We will find a solution, just be patient.

Thank you
